add: 購読しているポッドキャストを追加
it-trio/engineer-designer-podcast-rss pull request #3
Opened 2024-01-23 15:41 UTC by oikwsat

自分が購読しているエンジニア系のポッドキャスト9個追加してみました。
ローカルで動作確認済みです

※ ITトリオの日常、毎週聞いています！ ウラガワも楽しませて頂いてます🤘

2024-01-23 19:41 UTC, Spice-Z requested changes
PRありがとうございます！🥰

一部追加対象外としたい番組があったのでコメントしました。
それらの番組を削除していただきたいです🙏

2024-01-23 19:41 UTC, Spice-Z commented on src/resources/feed-info-list.ts
> +  ['rel.ax', 'https://anchor.fm/s/e644aa34/podcast/rss'],
企業が運営しているポッドキャスト番組については別で管理しているので、こでは追加せずに

https://github.com/it-trio/it-company-podcast-rss-feed

にPR作ってもらってもいいでしょうか？

2024-01-23 19:41 UTC, Spice-Z commented on src/resources/feed-info-list.ts
> +  ['texta.fm', 'https://anchor.fm/s/330a9488/podcast/rss'],
https://github.com/it-trio/it-company-podcast-rss-feed
で登録しているのでここでは追加しない、でお願いします

2024-01-23 19:41 UTC, Spice-Z commented on src/resources/feed-info-list.ts
> +  ['Ossan.fm', 'https://ossan.fm/feed.xml'],
READMEの[番組追加の方針](https://github.com/it-trio/engineer-designer-podcast-rss?tab=readme-ov-file#%E7%95%AA%E7%B5%84%E8%BF%BD%E5%8A%A0%E3%81%AE%E6%96%B9%E9%87%9D)に書いたのですが、
条件の
「番組の内容が、少しでもエンジニアリングやデザインについて触れていること」
を満たしていなさそうなので、
ここでは追加しない、でお願いします

2024-01-24 00:52 UTC, oikwsat commented on src/resources/feed-info-list.ts
> +  ['rel.ax', 'https://anchor.fm/s/e644aa34/podcast/rss'],
企業運営のフィード削除しました

2024-01-24 00:52 UTC, oikwsat commented on src/resources/feed-info-list.ts
> +  ['texta.fm', 'https://anchor.fm/s/330a9488/podcast/rss'],
こちらの企業運営のフィードも削除

2024-01-24 00:55 UTC, oikwsat commented on src/resources/feed-info-list.ts
> +  ['Ossan.fm', 'https://ossan.fm/feed.xml'],
了解です！ 言われてみるとほとんど触れられていない気がしますので削除しました

2024-01-24 00:58 UTC, Spice-Z approved these changes
修正ありがとうとざいます！

2024-01-24 00:58 UTC, merged